version: '3.8'

services:
  Web-Gen:
    image: 'cammd21/notification-service:1.5'
    container_name: 'notification-service'
    environment:
      - kafka-server=dory.srvs.cloudkafka.com:9094
      - register-topic=qufjdolb-register-topic
      - kafka-username=qufjdolb
      - kafka-password=hxvqD0Xc48ozIgF9dXWkW8qXBqQSD-dz
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  auth-service:
    image: 'cammd21/auth-service:1.3'
    container_name: 'auth-service'
    environment:
      - kafka-server=dory.srvs.cloudkafka.com:9094
      - kafka-username=qufjdolb
      - kafka-password=hxvqD0Xc48ozIgF9dXWkW8qXBqQSD-dz
      - database-url=jdbc:postgresql://postgres:5432/postgres
      - database-username=postgres
      - database-password=mysecretpassword
      - origin=http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: 'postgres'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
